version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: api/Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    env_file:
      - .env
    ports:
      - "8501:8501"
    depends_on:
      - backend
    restart: always