version: "3.9"

services:
  backend:
    build: ./backend
    image: insurance-virtual-agent-backend:latest
    ports:
      - "8080:8080"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
    working_dir: /app
    
    restart: always

  frontend:
    build: ./frontend
    image: insurance-virtual-agent-frontend:latest
    ports:
      - "8501:8501"
    depends_on:
      - backend
    restart: always
    working_dir: /app
    
